import './style.css';

const sections = [
  { group: 'Start here', items: [['overview', 'Overview'], ['getting-started', 'Getting started']] },
  { group: 'Learn', items: [['template-engine', 'Template engine'], ['architecture', 'Architecture'], ['templates', 'Template packages'], ['graphs', 'Graphs & context']] },
  { group: 'Reference', items: [['cli', 'CLI & MCP'], ['status', 'Status']] },
];
const pages = {
  overview: { eyebrow: 'TPLAIter / DEVELOPMENT PREVIEW', title: 'Give your agent building blocks.', intro: 'Use MCP to turn intent into template-backed code, with less repeated generation and focused context. The intended workflow keeps the result reviewable for local, budget-conscious, and frontier models.', hero: true, blocks: [{ id: 'workflow', title: 'Intent → request → blocks → validation', body: 'Describe the outcome, send an MCP request for parameters and blocks, render a project shape, then validate the manifest and generated language project. The current preview demonstrates the template and validation direction; it does not claim a complete live lifecycle or MCP experience.' }, { id: 'targets', title: 'Evaluation targets, not measured results', body: 'We are targeting 30% fewer coding and retrieval tokens through reusable parameterized blocks. Reliability and maintainability are unmeasured goals that need a defined evaluation.' }] },
  'getting-started': { eyebrow: 'START HERE', title: 'Explore a public development preview.', intro: 'The current core is an unreleased, public development snapshot. Use a reviewed checkout and the read-only workflow while lifecycle support is being completed.', blocks: [{ id: 'build', title: 'Build from a reviewed checkout', body: 'There is no public tagged release or compatibility promise yet. With Go 1.26 or newer, build the binary from the reviewed source checkout:', code: 'go build -o tplaiter .' }, { id: 'catalog', title: 'Inspect a registered catalog', body: 'A template repository must already be registered in the local tplAIter home. The checkpoint exposes `template list`, `template show`, and `template pull` for catalog inspection:', code: 'tplaiter template list\ntplaiter template show <ref>\ntplaiter template pull <ref> --dest ./template' }, { id: 'limits', title: 'Know the current boundary', body: 'Stock lifecycle commands can stop with TRUST_ANCHOR_MISSING or TRUST_LIFECYCLE_UNAVAILABLE. Live project creation and update are unavailable in this checkpoint, so this page intentionally stops at read-only exploration.' }] },
  'template-engine': { eyebrow: 'LEARN / TEMPLATE ENGINE', title: 'Go templates, kept simple.', intro: 'tplAIter uses Go’s standard text/template engine. Templates stay close to the files they produce, with explicit data and predictable rendering.', blocks: [{ id: 'syntax', title: 'A small template', code: '{{- if .ServiceName }}\npackage {{ .PackageName }}\n\n// {{ .ServiceName }} is ready to compose.\ntype {{ .ServiceName }} struct{}\n{{- end }}' }, { id: 'why', title: 'Why text/template', body: 'The engine is part of the Go standard library, needs no Python runtime, and makes the template boundary easy to review. Package authors can keep ordinary source files alongside their manifests.' }] },
  architecture: { eyebrow: 'LEARN / ARCHITECTURE', title: 'Packages compose; the engine stays focused.', intro: 'The system separates source templates, selection, and rendering so each layer can be inspected independently.', diagram: true, blocks: [{ id: 'flow', title: 'The flow', body: 'A repository exposes named template packages. A manifest describes inputs and outputs. The Go engine renders selected files into a destination. Optional graph data describes relationships around that materialization.' }] },
  templates: { eyebrow: 'LEARN / TEMPLATE PACKAGES', title: 'Four foundations for the preview.', intro: 'The public development preview is organized around independent packages. Each package can evolve on its own cadence.', cards: [['base', 'Base', 'Shared conventions and neutral building blocks.'], ['go', 'Go', 'A Go service foundation with idiomatic project shape.'], ['rust', 'Rust', 'A Rust service foundation for teams working in Rust.'], ['react', 'React + Next', 'Planned modifier path. React and the Next modifier are not shipped yet.']] },
  graphs: { eyebrow: 'LEARN / GRAPHS & CONTEXT', title: 'Make relationships visible.', intro: 'A local graph viewer and bounded context-pack work are available in the development preview for inspection, not a production service.', blocks: [{ id: 'scope', title: 'What is being explored', body: 'A source dependency DAG, an export selection graph, and optional post-render semantic context. These are separate concerns so ordinary rendering does not depend on graph analysis.' }, { id: 'availability', title: 'Availability', body: 'The viewer is a local standalone HTML tool in the preview. It reports syntax and declared evidence; it does not claim compiler resolution or invented call relationships.' }] },
  cli: { eyebrow: 'REFERENCE / CLI & MCP', title: 'Useful commands for inspection.', intro: 'The current checkpoint is best used to inspect template repositories and validate package structure. MCP is the intended selection interface, not a claim that the live lifecycle is complete.', table: [['Command', 'Purpose'], ['tplaiter template list', 'List registered repositories and packages'], ['tplaiter template show <ref>', 'Show a package manifest and metadata'], ['tplaiter template pull <ref>', 'Copy a template tree to disk for study'], ['tplaiter lint-template', 'Run template repository self checks'], ['tplaiter stats', 'Show project drift statistics'], ['tplaiter mcp-server', 'Expose preview CLI tools over stdio JSON-RPC']] },
  status: { eyebrow: 'REFERENCE / STATUS', title: 'An engineering development preview.', intro: 'The core is being prepared as a clean, independently reviewed source tree. The docs site is an independent presentation layer.', status: true },
};
function renderNav(active, query = '') { const q = query.toLowerCase(); const visible = sections.flatMap(({ items }) => items.filter(([, label]) => label.toLowerCase().includes(q))); return `${sections.map(({ group, items }) => { const rows = items.filter(([, label]) => label.toLowerCase().includes(q)); return rows.length ? `<div class="nav-group"><span class="nav-label">${group}</span>${rows.map(([id, label]) => `<a class="nav-link ${active === id ? 'active' : ''}" href="#${id}" data-page="${id}">${label}</a>`).join('')}</div>` : ''; }).join('')}${query && !visible.length ? '<div class="no-results">No pages found.<br><button id="clear-search">Clear search</button></div>' : ''}`; }
function codeBlock(code) { return `<div class="code-wrap"><button class="copy" data-copy="${encodeURIComponent(code)}">Copy</button><pre><code>${code.replaceAll('&', '&amp;').replaceAll('<', '&lt;')}</code></pre></div>`; }
function toc(page) { const entries = page.blocks?.filter(b => b.id).map(b => `<a href="#${b.id}">${b.title}</a>`) || []; return entries.length ? `<aside class="toc"><span>On this page</span>${entries.join('')}</aside>` : ''; }
function renderPage(id) { const p = pages[id] || pages.overview; let body = ''; if (p.hero) body = `<div class="hero-art" id="principles"><div class="hero-grid"></div><div class="hero-chip">template → project <span>↗</span></div><div class="hero-lines"><i></i><i></i><i></i><i></i></div></div><div class="feature-row"><div><strong>Composable by design</strong><span>Package boundaries that stay visible.</span></div><div><strong>Go-native</strong><span>text/template, no Python runtime.</span></div><div><strong>Inspectable</strong><span>Read the shape before you render.</span></div></div>`; if (p.blocks) body += p.blocks.map((b) => `<section class="content-block" id="${b.id}"><h2><a class="anchor" href="#${b.id}">#</a>${b.title}</h2>${b.code ? codeBlock(b.code) : `<p>${b.body}</p>`}</section>`).join(''); if (p.diagram) body += `<div class="diagram" id="flow"><div>source<br><small>template files</small></div><b>→</b><div>selection<br><small>manifest + exports</small></div><b>→</b><div>render<br><small>Go text/template</small></div></div>`; if (p.cards) body = `<div class="card-grid">${p.cards.map(([key, title, desc]) => `<article class="template-card"><span class="card-key">${key}</span><h2>${title}</h2><p>${desc}</p></article>`).join('')}</div>`; if (p.table) body = `<div class="ref-table">${p.table.map((r, i) => `<div class="table-row ${i === 0 ? 'head' : ''}"><span>${r[0]}</span><span>${r[1]}</span></div>`).join('')}</div>`; if (p.status) body = `<div class="status-list"><div><span class="dot amber"></span><strong>Public core preview</strong><span>Under active development</span></div><div><span class="dot green"></span><strong>Go text/template</strong><span>Current rendering model</span></div><div><span class="dot gray"></span><strong>Live new / update</strong><span>Not available in this checkpoint</span></div><div><span class="dot gray"></span><strong>Graph viewer</strong><span>Available in the preview</span></div></div><p class="note">Read-only commands and template authoring references are the supported starting point while lifecycle and trust registration work continues.</p>`; return `<div class="page-head"><div class="eyebrow">${p.eyebrow}</div><h1>${p.title}</h1><p class="intro">${p.intro}</p></div><div class="page-body">${body}</div>`; }
function app() { const requested = location.hash.slice(1); const initial = pages[requested] ? requested : 'overview'; if (requested && !pages[requested]) history.replaceState(null, '', '#overview'); document.querySelector('#app').innerHTML = `<header class="topbar"><a href="#overview" class="brand"><img src="/logo.png" alt="tplAIter" /><span>docs</span></a><div class="top-actions"><button class="icon-btn" id="theme" aria-label="Toggle color theme" aria-pressed="false">☼</button><a class="github" href="https://github.com/tplAIter" target="_blank" rel="noreferrer">GitHub ↗</a><button class="menu" id="menu" aria-label="Open navigation">☰</button></div></header><div class="layout"><aside id="sidebar"><div class="search"><span>⌕</span><input id="search" placeholder="Search docs" aria-label="Search docs" /><kbd>⌘ K</kbd></div><nav>${renderNav(initial)}</nav><div class="aside-foot">tplAIter <span>·</span> development preview</div></aside><main><div class="mobile-crumb">Documentation <span> / </span> <b id="crumb">${pages[initial].title}</b></div><div class="article-layout"><article id="content">${renderPage(initial)}</article>${toc(pages[initial])}</div><footer><span>tplAIter documentation</span><span>Built for clear boundaries.</span></footer></main></div>`; bind(); }
function bind() { const theme = document.querySelector('#theme'); if (localStorage.getItem('tplaiter-theme') === 'dark') document.body.classList.add('dark'); const sync = () => { const dark = document.body.classList.contains('dark'); theme.setAttribute('aria-pressed', dark); theme.textContent = dark ? '☾' : '☼'; }; sync(); theme.onclick = () => { document.body.classList.toggle('dark'); localStorage.setItem('tplaiter-theme', document.body.classList.contains('dark') ? 'dark' : 'light'); sync(); }; const menu = document.querySelector('#menu'); menu.onclick = () => { const side = document.querySelector('#sidebar'); side.classList.toggle('open'); menu.setAttribute('aria-expanded', side.classList.contains('open')); }; const search = document.querySelector('#search'); search.oninput = e => { document.querySelector('#sidebar nav').innerHTML = renderNav(location.hash.slice(1), e.target.value.trim()); bindNav(); }; search.onkeydown = e => { if (e.key === 'Escape') { search.value = ''; search.oninput({ target: search }); search.blur(); } }; bindNav(); document.addEventListener('click', async e => { if (e.target.matches('#clear-search')) { search.value = ''; search.oninput({ target: search }); search.focus(); } if (e.target.matches('.copy')) { await navigator.clipboard.writeText(decodeURIComponent(e.target.dataset.copy)); e.target.textContent = 'Copied'; setTimeout(() => e.target.textContent = 'Copy', 1200); } }); document.addEventListener('keydown', e => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); search.focus(); search.select(); } }); }
function bindNav() { document.querySelectorAll('[data-page]').forEach(a => a.onclick = e => { e.preventDefault(); location.hash = a.dataset.page; document.querySelector('#sidebar').classList.remove('open'); }); }
function navigate() { const requested = location.hash.slice(1); const id = pages[requested] ? requested : 'overview'; if (id !== requested) history.replaceState(null, '', '#overview'); document.querySelector('#content').innerHTML = renderPage(id); document.querySelector('#sidebar nav').innerHTML = renderNav(id); document.querySelector('#crumb').textContent = pages[id].title; document.querySelector('.toc')?.remove(); document.querySelector('.article-layout').insertAdjacentHTML('beforeend', toc(pages[id])); bindNav(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
window.addEventListener('hashchange', navigate); app();
